language: csharp
solution: HelloGrpc.sln
mono: none
dotnet: 2.2.401
install: 
 - dotnet restore
#  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
 - dotnet build
 - dotnet test .\Hello.Test\Hello.Test.csproj 
#  - msbuild /p:Configuration=Release HelloGrpc.sln
#  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./Hello.Tests/bin/Release/Hello.Tests.dll